### ISSUE TITLE
Sync profile with GitHub 

### ISSUE THREAD

**Issue by marianitadn** [rosedu/challenge#49]
My profile is not synced with GitHub.

For example my location is the old one:
![screenshot 2015-01-25 22 17 08](https://cloud.githubusercontent.com/assets/1681405/5893086/f23a5b80-a4df-11e4-8e8e-156faeb952d2.png)

**Comment by iulianR** [comment]
@marianitadn Link not found.

**Comment by marianitadn** [comment]
@iulianR am adaugat poza direct. :)

**Comment by mariuscoto** [comment]
@marianitadn please test this

**Comment by marianitadn** [comment]
:+1:
