### ISSUE TITLE
Create Game Rules

### ISSUE THREAD

**Issue by maria** [rosedu/challenge#71]
## Rules of Conduct

1. All contributions must be made during the competition and will not be submitted in other competitions organised by ROSEdu or in partnership with ROSEdu.
2. Pull Requests / Contributions which imply adding / deleting / updating a library inside the project, example: bootstrap, jquery, will have a score equal with 0. This doesn't apply when a library is modified to solve a bug and the fix can't be submitted for the original project, the project mentor will score the contribution with a score greater or equal with 0.
3. Each Pull Request / Contribution should solve a single bug, issue, feature.
4. Each workflow should take in consideration the repository guidelines for contributing. If no guide is explicitly stated, the participant should use the Github Flow - https://guides.github.com/introduction/flow/.

[Later edit] 

## Terms and conditions

1. ROSEdu challenge is for everyone, regardless of gender, sexual orientation, disability, physical appearance, body size, race, or religion. 
2. Participants have to have Romanian residency at the time of the competition, if a winner is not able to receive their prize in person the prize will be sent via a courier, only in Romania.
 (asta e pentru ca nu cred ca avem o idee clara despre cum sa oferim premii persoanelor ce nu sunt cetateti ai Romaniei sau care nu se supun regulilor noastre (rezidenti), precum nici infrastructura sa livram premii la mii de km departare)

3. A contributor can win a single prize, so she/he will be considered a winner for a single project / group of projects, the organisation team will decided for what project / group of projects the person will be elected as a winner.
4. ROSEdu is not liable for any additional taxes which have to be paid for the prizes, the winners have to pay any additional taxes for the prize they receive - regarding the Romanian laws.

**Comment by maria** [comment]
cc @mariuscoto @iulianR what do you think? do you have something to add?

**Comment by mariuscoto** [comment]
looks good

**Comment by iulianR** [comment]
Nothing to add. Looks good except some small issues/typos on items 3 and 4 of "Terms and conditions".
