### ISSUE TITLE
Register an OAuth consumer with wikimedia

### ISSUE THREAD

**Issue by strainu** [rosedu/challenge#86]
Pentru a putea accesa autentificarea pe gerrit.wikimedia.org trebuie să cerem un consumator la https://wikitech.wikimedia.org/wiki/Special:OAuthConsumerRegistration/propose (necesită autentificare). Sunt câteva câmpuri pe care eu nu știu să le completez: 
- OAuth "callback" URL
- Types of grants being requested , cu opțiunile de mai jos. Cred că a prima opțiune e cea mai bună, pentru că match-ul se poate face după username
  - Authentication only, no API access.
  - Authentication only with access to real name and email address via Special:OAuth/identify, no API access.
  - Request authorization for specific permissions.
- Usage restrictions (JSON) - aici pare că se introduc adresele IP de unde poate fi folosită aplicația; cred că putem să lăsăm 0.0.0.0/0
- Public RSA key

E nevoie de intervenție umană și deci o să dureze câteva zile. Dacă-mi ziceți ce user ați folosit pot să dau un mail să încerc să grăbesc lucrurile.

**Comment by strainu** [comment]
Ping?

**Comment by maria** [comment]
1. OAuth callback URL: ```http://challenge.rosedu.org/auth/gerrit```
2. Request authorization for specific permissions: request access to get it's pull requests and real name + email address.
3. IP: 141.85.227.138/32 si 127.0.0.1 - sa putem testa
4. Public RSA Key for?

**Comment by strainu** [comment]
Thank you. 
Public RSA key: OAuth requires that requests be signed; this can be done by using a shared secret, or by using public-key cryptography. If you want to use the latter, provide a public key here.
More details: https://tools.wmflabs.org/oauth-hello-world/

Should I register for one without RSA key?

**Comment by strainu** [comment]
These can be changed after the fact. I submitted the request without them and pasted the consumer and secret token on slack.

**Comment by maria** [comment]
The shared secret will be the client secret key?

**Comment by strainu** [comment]
Yes, I believe so. See the example frompassport-mediawiki: https://github.com/wikimedia/passport-mediawiki/blob/master/examples/oauth/app.js

**Comment by strainu** [comment]
Please be aware that the app was approved: https://wikitech.wikimedia.org/wiki/Special:OAuthListConsumers/view/417e6dbe84c69065cd4937f3bdc83503

The admin said the following: "auth + email access only; would prefer remote to use https but not worth blocking at this point". I know you guys have a plan to put https on rosedu.org, so when you do that, let me know and I'll update the app.
